apiVersion: extensions.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: shoot-flux
  namespace: shoot--local--flux
spec:
  type: shoot-flux
  providerConfig:
    apiVersion: flux.extensions.gardener.cloud/v1alpha1
    kind: FluxConfig
    flux:
      version: v2.1.2 # defaults to some current version, not latest!
      registry: ghcr.io/fluxcd
      namespace: flux-system
      # components: ["helm-controller", "kustomize-controller", "source-controller"]
      componentsExtra:
        - source-watcher
    # additionalSecretResources:
    #   - name: shoot-vault-secret
    #     targetName: vault
    source:
      gitRepository:
        template:
          apiVersion: source.toolkit.fluxcd.io/v1
          kind: GitRepository
          spec:
            ref:
              branch: main
            # secretRef:
            #  name: flux-system
            url: https://github.com/fluxcd/flux2-kustomize-helm-example
        # secretResourceName: flux-ssh-secret

      # Alternatively, use an OCI repository:
      # ociRepository:
      #   template:
      #     apiVersion: source.toolkit.fluxcd.io/v1
      #     kind: OCIRepository
      #     spec:
      #       url: oci://ghcr.io/example/manifests
      #       ref:
      #         semver: '>= 1.0.0'
      #         # or use tag: v1.0.0
      #         # or use digest: sha256:abcd1234...
      #       interval: 10m
      #     # secretRef:
      #     #   name: flux-system
      #   # secretResourceName: oci-credentials
    kustomization:
      template:
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        spec:
          path: clusters/production/flux-system
