apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: shoot-flux
spec:
  resources:
  - kind: Extension
    type: shoot-flux
    lifecycle:
      reconcile: AfterWorker
  deployment:
    extension:
      helm:
        ociRepository:
          repository: ghcr.io/stackitcloud/charts/gardener-extension-shoot-flux
          tag: latest
